// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-HgqTRxadBwbfTH1-pQ7Dcj1r912Tc2Y',
    appId: '1:846676066899:web:99f11da31117a2a94a3ca6',
    messagingSenderId: '846676066899',
    projectId: 'things-stuff-206ca',
    authDomain: 'things-stuff-206ca.firebaseapp.com',
    storageBucket: 'things-stuff-206ca.appspot.com',
    measurementId: 'G-8XNLGZH73N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EHXI3N7Weo7pknBwh0i3JDUHcYunzI0',
    appId: '1:846676066899:android:3d5e0869968a7d564a3ca6',
    messagingSenderId: '846676066899',
    projectId: 'things-stuff-206ca',
    storageBucket: 'things-stuff-206ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoVzQQHJ15laCqiR98DN0Zft-1-zeIu6w',
    appId: '1:846676066899:ios:c08ff045739f7a154a3ca6',
    messagingSenderId: '846676066899',
    projectId: 'things-stuff-206ca',
    storageBucket: 'things-stuff-206ca.appspot.com',
    iosClientId: '846676066899-33ufdv5p2kvcbuq5u1b30e1mpoc10li9.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsStuffClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoVzQQHJ15laCqiR98DN0Zft-1-zeIu6w',
    appId: '1:846676066899:ios:c08ff045739f7a154a3ca6',
    messagingSenderId: '846676066899',
    projectId: 'things-stuff-206ca',
    storageBucket: 'things-stuff-206ca.appspot.com',
    iosClientId: '846676066899-33ufdv5p2kvcbuq5u1b30e1mpoc10li9.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsStuffClient',
  );
}
